[package]
name = "firetrap"
version = "0.1.0"
authors = ["Koen Wilde <koen@chillheid.nl>"]
description = "Modern, safe and extensible FTP server library for Rust"
documentation = "https://docs.rs/firetrap/"
repository = "https://github.com/koenw/firetrap"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["ftp"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"
bytes = "0.4"
log = "0.4"
chrono = {version = "0.4", features = ["serde"]}
failure = "0.1"
failure_derive = "0.1"
pam-auth = { version = "0.5", optional = true }
path_abs = "0.4"
uuid = { version = "0.7", features = ["v4"] }

serde = { version="1.0.91", features=["derive"]}
serde_json = "1.0.39"
hyper = "0.12.28"
hyper-tls = "0.3.2"
sync_oauth2 = {path = "./examples/sync_oauth2", optional = true}
mime = {version = "0.3.13", optional = true}
url = { version = "1.7.2", optional = true }

[dev-dependencies]
tempfile = "3"
ftp = "3"
pretty_env_logger = "0.2"
pretty_assertions = "0.5"
rand = "0.6"
lazy_static = "1.1"

[features]
pam = ["pam-auth"]
oauth2 = ["sync_oauth2"]
cloud_storage = ["mime"]

[[example]]
name = "pam"
required-features = ["pam"]

[[example]]
name = "gcs"
required-features = ["oauth2", "cloud_storage"]